### ISSUE TITLE
Place navbar at the bottom

### ISSUE THREAD

**Issue by felixwetell** [Linda-Carlstad/lindacarlstad.se#100]
After reading up on UX/UI design principles, a common theme came up. The navigation is at the bottom on almost every mobile app, but not on web pages. 

Should we move the navbar to the bottom? 

Further reading:
- https://www.smashingmagazine.com/2019/08/bottom-navigation-pattern-mobile-web-pages/
- https://www.smashingmagazine.com/2016/11/the-golden-rules-of-mobile-navigation-design/
- https://www.nngroup.com/articles/mobile-navigation-patterns/

**Comment by Hortlund** [comment]
That is  a good idea, the website will get more of an "app like" feeling.
That is by implication then that the menu is at the same place for desktop sizes.
