### ISSUE TITLE
Länk till game dev community på innovationpark?

### ISSUE THREAD

**Issue by victorahsblomberg** [Linda-Carlstad/lindacarlstad.se#52]
Vore det inte nice att förmedla att det finns en plats på inno där folk som vill kan utveckla spel? Det finns två stationära datorer där att låna, musik utrustning, och en schysst lokal? 

http://www.thegreatjourney.se/

**Comment by felixwetell** [comment]
User can now see partners and all the information added to them, see commit [582afcf](https://github.com/Linda-Carlstad/lindacarlstad.se/commit/582afcf0a6dc426e7635b4ca8e5f97b0604841c2)
