### ISSUE TITLE
Change link to "Tentor"

### ISSUE THREAD

**Issue by felixwetell** [Linda-Carlstad/lindacarlstad.se#64]
Link "Tentor" is invalid and not longer working

**Comment by Tobbb** [comment]
Skickade all källkod för tentahub om ni vill lägga den på sidan, då kan länken va kvar. Dock kanske det är bättre att skriva om den eftersom den är skriven i codeigniter, dock är ju alla filer kvar. Seke och mexika har också filer där

**Comment by felixwetell** [comment]
@Tobbb vi ska försöka att integrera det, skapar ett nytt issue på det.

**Comment by felixwetell** [comment]
#65

**Comment by felixwetell** [comment]
Change link "Tentor" to point to https://tenta.lindacarlstad.se

**Comment by felixwetell** [comment]
Link have been changed directly on the server, should be changed in repo
