### ISSUE TITLE
Integrate "Tentahub"

### ISSUE THREAD

**Issue by felixwetell** [Linda-Carlstad/lindacarlstad.se#65]

**Comment by Hortlund** [comment]
Integreringen kommer att göras efter att vi har flyttat till beebyte, då lagringen på nuvarande hotell är ett problem. Preliminärt den 12:e augusti.

**Comment by felixwetell** [comment]
Tack för infon. Vi ser till att implementera det innan första tentan.

**Comment by felixwetell** [comment]
Tenta hub is added to a subdomain at https://tenta.lindacarlstad.se. 
Thanks to @Hortlund, nice job!
