### ISSUE TITLE
Improve error views 

### ISSUE THREAD

**Issue by felixwetell** [Linda-Carlstad/lindacarlstad.se#67]
Cool designs:
https://freefrontend.com/500-error-page-html-templates/

**Comment by Tobbb** [comment]
Kan sätta mig å göra förslag i helgen

**Comment by felixwetell** [comment]
Här har du felen vi täcker idag:
https://github.com/Linda-Carlstad/lindacarlstad.se/tree/master/resources/views/errors

Vore kul att implementera något i stil med det här:
https://codepen.io/cluzier/pen/RYMVBP 
Förslag på bibliotek är tillhörande [typed.js](https://github.com/mattboldt/typed.js/).

Gör en ny branch och en pull-request när du kodat klart. Sätt mig som reviewer så får jag en koll på om det är stilen vi är ute efter. 
**Happy coding!**
